### ISSUE TITLE
README has a wrong supported version for Blazor project

### ISSUE THREAD

**Issue by albx** [albx/KITT.Web.ReCaptcha#22]
In README files (both the main and the specific one of the Blazor project) the supported TargetFramework for the Blazor project is wrong.

Now it supports only .NET 8

**Comment by AngeloDotNet** [comment]
@albx this issue is resolved with PRs #23 and #24

**Comment by albx** [comment]
@AngeloDotNet thanks! I'll review the PRs in the next few days :)

**Comment by AngeloDotNet** [comment]
@albx this issue has been resolved with my last 2 open PRs.. 👍

**Comment by albx** [comment]
Yep!. Closing.
Thank you again
